src/models.py
from src import db, login_manager
from datetime import datetime
from flask_login import UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    def generate_reset_token(self, expires_sec=1800):
        s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)

    def __repr__(self):
        return f"User ('{self.username}','{self.email}', '{self.image_file}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    timestamp = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}','{self.timestamp}')"

src/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from src.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Username is already taken!')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('This email is already registered!')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class UpdateProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if not current_user.username == username.data:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That Username is already taken!')

    def validate_email(self, email):
        if not current_user.email == email.data:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('This email is already registered!')


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')


class ResetRequestForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Proceed')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if not user:
            raise ValidationError('This email is not registered. Sign Up now!')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Enter new Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Submit')

src/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

src/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from src.models import User
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Username is already taken!')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('This email is already registered!')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class UpdateProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if not current_user.username == username.data:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That Username is already taken!')

    def validate_email(self, email):
        if not current_user.email == email.data:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('This email is already registered!')


class ResetRequestForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Proceed')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if not user:
            raise ValidationError('This email is not registered. Sign Up now!')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Enter new Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Submit')

src/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from src.users.routes import users
    from src.posts.routes import posts
    from src.main.routes import main
    from src.errors.handlers import errors
    app.register_blueprint(users)
    app.register_blueprint(posts)
    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

src/main/routes.py
from flask import Blueprint, render_template, request
from src.models import Post

main = Blueprint('main', __name__)


@main.route('/')
def index():
    page = request.args.get('page', 1, type=int)

    posts = Post.query.order_by(Post.timestamp.desc()).paginate(per_page=5, page=page)
    return render_template('index.html', title='Home', posts=posts)


@main.route('/about')
def about():
    return render_template('about.html', title='About Us')


@main.route('/contact')
def contact():
    return render_template('contact.html', title='Contact')

src/posts/routes.py
from flask import Blueprint, flash, request, render_template, redirect, url_for, abort
from flask_login import current_user, login_required
from src import db
from src.posts.forms import PostForm
from src.models import Post

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.index'))
    return render_template('create_post.html', title='Create Post', form=form, legend="Create Post")


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post Updated successfully!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend="Update Post")


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post Deleted successfully!', 'success')
    return redirect(url_for('main.index'))

src/users/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from src.users.forms import LoginForm, RegistrationForm, UpdateProfileForm, ResetRequestForm, ResetPasswordForm
from flask_login import current_user, login_required, login_user, logout_user
from src.models import User, Post
from src import db, bcrypt
from src.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Account Created Successfully', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form, title='Register')


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, form.remember_me.data)
            next_page = request.args.get('next')
            flash(f'Logged in as {user.username}', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Invalid Email Id or password', 'danger')
    return render_template('login.html', form=form, title='Login')


@users.route('/logout')
def logout():
    if current_user.is_authenticated:
        logout_user()
        flash('Logged Out successfully!')
    else:
        flash('You are not currently logged in!')
    return redirect(url_for('main.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateProfileForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account Updated Successfully', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_post(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.timestamp.desc()).paginate(per_page=5, page=page)
    return render_template('user_posts.html', title=user.username, posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def request_reset():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = ResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(f'An email has been sent to {user.email}. Follow the instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Your token is either invalid or has been expired.')
        return redirect(url_for('users.request_reset'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  {% if title %}
    <title>{{ title }}-B4U</title>
  {% else %}
    <title>FlaskBlog</title>
  {% endif %}

  <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{{ url_for('static', filename='css/clean-blog.min.css') }}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Blog 4 You</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.contact') }}">Contact</a>
          </li>
          {% if current_user.is_anonymous %}
		      <li class="nav-item">
		        <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
		      </li>
          {% endif %}
          </ul>
      </div>
      {% if current_user.is_authenticated %}
    <div class="dropdown">
                  <button style="color: white;" class="btn btn-outline dropdown-toggle"  id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img class="rounded-circle" src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}" height="30" width="30"></button>
                  <div class="dropdown-menu">
                    <a class="nav-link" href="{{ url_for('users.account') }}">My Profile</a>
                    <div class="dropdown-divider"></div>
                    <a class="nav-link" href="{{ url_for('posts.create_post') }}">New Post</a>
                    <a class="nav-link" href="{{ url_for('users.user_post', username=current_user.username) }}">My Posts</a>
                    <div class="dropdown-divider"></div>
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                 </div>
                </div>
    {% endif %}
    </div>
  </nav>


  <!-- Page Header -->

  {% block head %}
  {% endblock %}

  <!-- Main Content -->
  <div class="container">
      <div class="row">
         <div class="col-lg-8 col-md-10 mx-auto">
           {% block content %}
           {% endblock %}
         </div>
      </div>
  </div>
  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-linkedin-in fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Blog 4 You 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Modal Content -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
        <p class="modal-title" id="exampleModalLabel">
          {% with messages=get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category,message in messages %}
                <p class="alert alert-{{ category }}">{{ message }}</p>
              {% endfor %}
            {% endif%}
          {% endwith %}
        </p>
</div>

  <!-- Bootstrap core JavaScript -->
  <script src="{{url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Custom scripts for this template -->
  <script src="{{url_for('static', filename='js/clean-blog.min.js') }}"></script>
  <script>
  {% with messages=get_flashed_messages() %}
    {% if messages %}
        $(document).ready(function(){
          $("#exampleModal").modal('show');
          });
    {% endif%}
  {% endwith %}
  </script>

</body>

</html>

src/templates/email_verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}


{% block head %}
    <header class="masthead" style="background-image: url({{ url_for('static', filename='img/home-bg.jpg') }})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Blog 4 You</h1>
            <span class="subheading">Writing is the painting of the voice.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
    {% if posts %}
        {% for post in posts.items %}

                     <div class="post-preview">
                     <h2 class="post-title"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                     <p class="post-subtitle">{{ post.content }}</p>
                     <p class="post-meta"><img class="rounded-circle" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" height="50" width="50">
                        Posted by <a href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.timestamp.strftime('%Y-%m-%d') }}</p>
                     </div>

        <hr>
         {% endfor %}
    {% endif %}
    <div class="m-4" align="center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current =1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info" href="{{ url_for('main.index', page=page_num) }}">{{ page_num  }}</a>
            {% else %}
                <a class="btn btn-outline-info" href="{{ url_for('main.index', page=page_num) }}">{{ page_num  }}</a>
            {% endif %}
        {% else %}
               ...
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}

src/templates/login.html
{% extends 'base.html' %}
{% block head %}
    <header class="masthead" style="background-image: url({{ url_for('static', filename='img/home-bg.jpg') }})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Sign In</h1>
            <span class="subheading">It's the possibility of having a dream come true that makes life interesting.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <form action="" method="post">
            {{ form.hidden_tag() }}
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                {{ form.email.label }}
                {{ form.email(size=32, placeholder='Email') }}
                {% for error in form.email.errors%}
                <p class="help-block text-danger">[{{ error }}]</p>
                {% endfor %}
            </div>
        </div>
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                {{ form.password.label }}<br>
                {{ form.password(size=32, placeholder='Password') }}
                {% for error in form.password.errors%}
                <p class="help-block text-danger">[{{ error }}]</p>
                 {% endfor %}
            </div>
        </div>
        <div class="control-group mt-4">
            <div class="form-group form-check">
                {{ form.remember_me() }}
                <small class="text-muted">{{ form.remember_me.label }}</small>
            </div>
        </div>
        <div id="success"></div>
    <div class="form-group">
        {{ form.submit(class='btn btn-outline-info') }}
    <small class="text-muted m-1"><a href="{{ url_for('users.request_reset') }}">Forgot Password?</a></small>
    </div>
        </form>
          <small class="text-muted">New User? <a href="{{ url_for('users.register')}}">Sign Up here!</a></small>
      </div>
    </div>
</div>


{% endblock %}

src/templates/post.html
{% extends 'base.html' %}


{% block head %}
    <header class="masthead" style="background-image: url({{ url_for('static', filename='img/post-bg.jpg') }})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>Man must explore, and this is exploration at its greatest</h1>
            <h2 class="subheading">Explore our blog for more exciting content</h2>
            <span class="meta">-Team (Blog 4 You)</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}


{% block content %}
        <div class="card m-4">
            <article class="media-content-section m-4">
                <div class="media-body">
                    <div class="article-metadata">
                        <img class="rounded-circle" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" height="50" width="50">
                        <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>
                        <small class="text-muted">{{ post.timestamp.strftime('%Y-%m-%d') }}</small>
                        {% if post.author == current_user %}
                        <div class="mt-4">
                            <a class="btn btn-outline-info btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id = post.id) }}">Update</a>
                            <button type="button" class="btn btn-outline-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                        </div>
                        {% endif %}
                        <hr>
                    </div>
                    <h2 class="article-title">{{ post.title }}</h2>
                    <p class="article-content">{{ post.content }}</p>
                </div>
            </article>
        </div>
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        This post will be deleted permanently. Are you sure you want to continue?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="post">
                            <input class="btn btn-danger" type="submit" value="Delete">
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

src/templates/user_posts.html
{% extends 'base.html' %}


{% block head %}
<header class="masthead" style="background-image: url({{ url_for('static', filename='img/home-bg.jpg') }})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Posts by {{ user.username }} ({{ posts.total }})</h1>
            <span class="subheading">Writing is the painting of the voice.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
    {% if posts %}
        {% for post in posts.items %}
        <div class="card m-4">
            <article class="media-content-section m-4">
                <div class="media-body">
                    <div class="article-metadata">
                        <img class="rounded-circle" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" height="50" width="50">
                        <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>
                        <small class="text-muted">{{ post.timestamp.strftime('%Y-%m-%d') }}</small><hr>
                    </div>
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                    <p class="article-content">{{ post.content }}</p>
                </div>
            </article>
        </div>
         {% endfor %}
    {% endif %}
    <div class="m-4" align="center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current =1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info" href="{{ url_for('users.user_post',username=user.username, page=page_num) }}">{{ page_num  }}</a>
            {% else %}
                <a class="btn btn-outline-info" href="{{ url_for('users.user_post',username=user.username, page=page_num) }}">{{ page_num  }}</a>
            {% endif %}
        {% else %}
               ...
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}